# 一、生成二维码 qrcode

qrcode 是一个用于生成二维码的 Python 库，支持简单的二维码生成，同时提供自定义二维码大小、错误校正等配置选项。它可以创建包含文本、数字、URL等内容的二维码，生成的二维码可以保存为图片或在程序中进一步处理。

"""
-- Barcode(条形码) 与 QRCode(二维码)
1. 数据存储结构
条形码：一维结构，由宽度不等的平行条纹（通常是黑白条）组成，数据仅在水平方向（X轴）编码。条形码信息存储量较小，通常用于存储少量数字或字母，比如商品的 ID 或价格。
二维码：二维结构，由黑白方块组成，数据在水平和垂直方向（X轴和Y轴）同时编码。二维码可以存储较多数据，包括文本、URL、数字、甚至二进制数据。
2. 数据容量
条形码：容量较小，通常在 20-30 个字符以内，最多可存储 43 个字符的简单编码数据。
二维码：容量较大，可以存储数千个字符（具体取决于编码的复杂程度和所使用的纠错级别）。比如，标准的 QR 码可以存储多达 4,296 个字母或 7,089 个数字。
3. 识别速度与纠错能力
条形码：条形码的识别速度较快，但纠错能力较差，任何破损或模糊都可能导致扫描失败。
二维码：二维码有较高的纠错能力，即使部分二维码破损、污损或存在部分遮挡，也能正确解码。二维码有四个纠错等级（L、M、Q、H），最高可修复 30% 的数据损坏。
4. 占用空间
条形码：由于是单维结构，条形码长度较长，占用水平空间较多，但在高度上较小。
二维码：二维码占用的是方形空间，视觉上更紧凑，适合较小的区域。
5. 常见类型
条形码：包括常见的 EAN-13、UPC-A、Code 39、Code 128 等，用于零售商品、图书编号等。
二维码：包括 QR 码（最常用）、Data Matrix、Aztec 码和 PDF417 等。QR 码在广告、支付、物流等领域广泛应用。
"""

In [12]:
import qrcode

In [13]:
data = "https://www.tttttttttt.com"

In [14]:
"""
version: 控制二维码的大小。1 是最小的大小，40 是最大。设置 fit=True 可以自动调整大小。
error_correction: 控制二维码的错误校正能力：
    ERROR_CORRECT_L：7% 容错（最低）
    ERROR_CORRECT_M：15% 容错
    ERROR_CORRECT_Q：25% 容错
    ERROR_CORRECT_H：30% 容错（最高）
box_size: 控制二维码每个小格的像素数，影响生成的二维码的图像尺寸。
border: 控制二维码边框的厚度（以格为单位），推荐至少设置为 4。
"""

qr = qrcode.QRCode(
    version=1, 
    error_correction=qrcode.constants.ERROR_CORRECT_L, 
    box_size=10, 
    border=4)

In [15]:
# 添加数据到二维码
qr.add_data(data)
qr.make(fit=True)

In [16]:
# 生成图像
img = qr.make_image(fill='black', back_color='white')

In [17]:
# img.show()

In [18]:
img.save("simple_qrcode.png")

In [19]:
import cv2
import numpy as np

img_cv = np.array(img.convert("RGB"))

In [20]:
img_cv.shape

(330, 330, 3)

In [21]:
from matplotlib import pyplot as plt

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(img_cv, cmap="gray")

# 二、qrcode 解码 opencv

In [22]:
# 解码二维码
detector = cv2.QRCodeDetector()

In [23]:
"""
data：返回的解码数据（字符串类型），即从二维码中提取的原始信息
vertices：一个包含二维码四个顶点坐标的数组（形状是 (4, 2)）。这些顶点坐标表示二维码图像的外框位置，按顺序返回。vertices 由四个 (x, y) 坐标组成，
    这些坐标可以用于进一步的图像处理或几何变换（例如透视变换）; 这个数组表示二维码的四个顶点坐标，从左上角开始，按顺时针顺序排列。
_: 返回的是一个 25x25 的 numpy 数组，表示二维码图像的一个 "平直" 或 "标准" 版本。它与二维码图像中的每个像素进行对应，
    代表了二维码矩阵中的一个二进制值矩阵，显示了二维码图像的每个模块（例如黑白格子）的状态。具体来说，它是二维码的 "标准化" 图像
"""
data, vertices, _ = detector.detectAndDecode(img_cv)

In [24]:
data

'https://www.tttttttttt.com'

In [25]:
vertices

array([[[ 40.     ,  40.     ],
        [288.99997,  40.     ],
        [288.99997, 288.99997],
        [ 40.     , 288.99997]]], dtype=float32)

In [26]:
_.shape

(25, 25)

In [27]:
from matplotlib import pyplot as plt

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(_, cmap="gray")

In [28]:
""" detect() 函数的主要作用是 检测二维码在图像中的位置，它返回二维码的位置点坐标
retval: 返回一个布尔值，表示是否成功检测到二维码
points: 返回一个包含二维码角点位置的列表, points 是一个 numpy 数组，形状为 (n, 4, 2)，其中 n 是检测到的二维码数量。
"""
retval, points = detector.detect(img_cv)

In [29]:
retval

True

In [30]:
points

array([[[ 40.     ,  40.     ],
        [288.99997,  40.     ],
        [288.99997, 288.99997],
        [ 40.     , 288.99997]]], dtype=float32)

# 三、DataMatrix码

    """
    pip install pylibdmtx
    
    apt-get install libdmtx0a libdmtx-dev
    """


In [136]:
# 显示图像
img = cv2.imread("datamatrix.png", cv2.IMREAD_GRAYSCALE)
# plt.imshow(img, cmap='gray')
# plt.axis('off')  # 不显示坐标轴
# plt.show()

In [69]:
from pylibdmtx.pylibdmtx import encode
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

In [74]:
# 生成 DataMatrix 码
data = "Hello, DataMatrix!"
# 使用 pylibdmtx 编码
encoded = encode(data.encode('utf-8'))

In [76]:
# 将编码的数据转换为 PIL 图像
datamatrix_img = Image.frombytes('RGB', (encoded.width, encoded.height), encoded.pixels)

In [78]:
# 保存图片
datamatrix_img.save("datamatrix.png")

In [135]:
# 显示图片
# datamatrix_img.show()

In [134]:
# 显示图像
# plt.imshow(datamatrix_img, cmap='gray')
# plt.axis('off')  # 不显示坐标轴
# plt.show()

In [85]:
# 将 PIL 图像转换为 numpy 数组
image_array = np.array(datamatrix_img)

# 输出 numpy 数组的形状，即图像的 shape
print("Image shape:", image_array.shape)

Image shape: (110, 110, 3)


In [86]:
datamatrix_img.size

(110, 110)

In [89]:
datamatrix_img.mode

'RGB'

In [91]:
# 根据图像模式推断通道数
mode_to_channels = {
    "1": 1,      # 1-bit pixels, black and white
    "L": 1,      # 8-bit pixels, grayscale
    "P": 1,      # 8-bit pixels, mapped to palette
    "RGB": 3,    # 3x8-bit pixels, true color
    "RGBA": 4,   # 4x8-bit pixels, true color with transparency mask
    "CMYK": 4,   # 4x8-bit pixels, color separation
    "YCbCr": 3,  # 3x8-bit pixels, color video format
    "LAB": 3,    # 3x8-bit pixels, L*a*b color space
    "HSV": 3,    # 3x8-bit pixels, Hue, Saturation, Value
    "I": 1,      # 32-bit integer pixels
    "F": 1       # 32-bit floating point pixels
}

# 获取通道数
channels = mode_to_channels.get(datamatrix_img.mode, "Unknown")
print("Channels:", channels)

Channels: 3


In [133]:
from pylibdmtx.pylibdmtx import decode
from PIL import Image

# 加载包含 DataMatrix 码的图像
image = Image.open("datamatrix.png")

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(image, cmap="gray")

# 解码图像中的 DataMatrix 码
decoded_data = decode(image)

# 打印解码后的数据
if decoded_data:
    print("Decoded Data:", decoded_data[0].data.decode('utf-8'))
else:
    print("No DataMatrix code found in the image.")

Decoded Data: Hello, DataMatrix!


# 四、Zxing

python-zxing不能正常使用且已不再维护

"""

使用方案1：https://pypi.org/project/pyzxing

对应在代码仓库： https://github.com/ChenjieXu/pyzxing

使用方案2：python-zxing  https://pypi.org/project/zxing  实在原有的python-zxing上的新的维护：https://github.com/dlenski/python-zxing
"""

In [31]:
import zxing

In [32]:
zxing.__version__

'1.0.3'

In [33]:
reader = zxing.BarCodeReader()

In [34]:
print(reader.zxing_version, reader.zxing_version_info)

3.5.3 (3, 5, 3)


In [35]:
image = cv2.imread("./datamatrix.png")

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(image, cmap="gray")

barcode = reader.decode("./datamatrix.png")

In [36]:
barcode

BarCode(raw='Hello, DataMatrix!', parsed='Hello, DataMatrix!', raw_bits='49666d6d702d21456275624e6275736a7922', path='/root/project/research/code/datamatrix.png', format='DATA_MATRIX', type='TEXT', points=[(11.219178, 11.200866), (11.219178, 97.79752), (97.78082, 97.79594), (97.78082, 11.088031)])

In [37]:
image = cv2.imread("./simple_qrcode.png")

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(image, cmap="gray")

barcode = reader.decode("./simple_qrcode.png")

print(f"barcode: {barcode}")

barcode: BarCode(raw='https://www.tttttttttt.com', parsed='https://www.tttttttttt.com', raw_bits='41a68747470733a2f2f7777772e747474747474747474742e636f6d0ec11ec11ec11', path='/root/project/research/code/simple_qrcode.png', format='QR_CODE', type='URI', points=[(75.0, 255.0), (75.0, 75.0), (255.0, 75.0), (225.0, 225.0)])


In [38]:
image = cv2.imread("/root/dataset/code/new_oral/Image_20241031151938932.bmp")

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(image, cmap="gray")

barcode = reader.decode("/root/dataset/code/new_oral/Image_20241031151938932.bmp")

print(f"barcode: {barcode}")

barcode: BarCode(raw='010551AXDR90360361', parsed='010551AXDR90360361', raw_bits='690105336421382432635a24033d646a', path='/root/dataset/code/new_oral/Image_20241031151938932.bmp', format='CODE_128', type='TEXT', points=[(3091.0, 1596.0), (1994.0, 1596.0)])


In [129]:
# import os
# import tempfile

# image_folder = "/root/dataset/code/new_oral2/"
# nums = 0
# # 创建 ZXing 解码器
# reader = zxing.BarCodeReader()

# # 遍历文件夹中的所有文件
# for filename in os.listdir(image_folder):
#     image_path = os.path.join(image_folder, filename)
#     print(f"image_path: {image_path}")

#     image = Image.open(image_path)
#     # 将 PIL 图像转换为 NumPy 数组
#     image = np.array(image)
#     # 进行切片操作
#     image = image[2000:2000 + 1000, 1500: 1500 + 2000]

#     image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
#     # _, image = cv2.threshold(image, 128, 255, cv2.THRESH_BINARY)
    
#     with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as temp_file:
#         temp_file_path = temp_file.name
#         cv2.imwrite(temp_file_path, image)

#     print(f"temp_file_path: {temp_file_path}")
#     barcode = reader.decode(temp_file_path)
    
#     # 检查是否检测到条形码
#     if barcode.raw:
#         nums += 1
#         print(f"barcode: {barcode}")
#         # fig, ax = plt.subplots(figsize=(8, 8))
#         # ax.imshow(image, cmap="gray")        
#     else:
#         fig, ax = plt.subplots(figsize=(8, 8))
#         ax.imshow(image, cmap="gray")        
#         print("No barcode detected")
#         print(f"barcode: {barcode}")

In [128]:
# import os
# import tempfile

# image_folder = "/root/dataset/code/new_oral/"
# nums = 0
# # 创建 ZXing 解码器
# reader = zxing.BarCodeReader()

# # 遍历文件夹中的所有文件
# for filename in os.listdir(image_folder):
#     image_path = os.path.join(image_folder, filename)
#     print(f"image_path: {image_path}")

#     image = Image.open(image_path)
#     # 将 PIL 图像转换为 NumPy 数组
#     image = np.array(image)
#     # 进行切片操作
#     image = image[1500:1500 + 300, 1700: 1700 + 1500]

#     image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
#     # _, image = cv2.threshold(image, 146, 255, cv2.THRESH_BINARY)
    
#     with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as temp_file:
#         temp_file_path = temp_file.name
#         cv2.imwrite(temp_file_path, image)

#     print(f"temp_file_path: {temp_file_path}")
#     barcode = reader.decode(temp_file_path)
    
#     # 检查是否检测到条形码
#     if barcode.raw:
#         nums += 1
#         print(f"barcode: {barcode}")
#         # fig, ax = plt.subplots(figsize=(8, 8))
#         # ax.imshow(image, cmap="gray")        
#     else:
#         fig, ax = plt.subplots(figsize=(8, 8))
#         ax.imshow(image, cmap="gray")        
#         print("No barcode detected")
#         print(f"barcode: {barcode}")

# 五、wechat QRCode

In [39]:
import cv2
from cv2.wechat_qrcode import WeChatQRCode

In [40]:
detect_obj = cv2.wechat_qrcode_WeChatQRCode()
img = cv2.imread('./simple_qrcode.png')
res,points = detect_obj.detectAndDecode(img)
print('res:',res)
print('points:',points)

res: ('https://www.tttttttttt.com',)
points: (array([[ 40.,  40.],
       [290.,  40.],
       [290., 290.],
       [ 40., 290.]], dtype=float32),)


In [41]:
from cv2.wechat_qrcode import WeChatQRCode

detector = WeChatQRCode(
    detector_prototxt_path="./opencv_3rdparty/detect.prototxt", 
    detector_caffe_model_path="./opencv_3rdparty/detect.caffemodel", 
    super_resolution_prototxt_path="./opencv_3rdparty/sr.prototxt", 
    super_resolution_caffe_model_path="./opencv_3rdparty/sr.caffemodel")
img = cv2.imread("./simple_qrcode.png") 
res, points = detector.detectAndDecode(img)

print(res)
print(points)

('https://www.tttttttttt.com',)
(array([[ 40.,  40.],
       [290.,  40.],
       [290., 290.],
       [ 40., 290.]], dtype=float32),)


# 六、zbar qrcode

In [42]:
from pyzbar.pyzbar import decode
from PIL import Image


In [44]:
from pyzbar.pyzbar import decode
from PIL import Image

# 读取生成的条形码图像

image = cv2.imread("./simple_qrcode.png")

# fig, ax = plt.subplots(figsize=(8, 8))
# ax.imshow(image, cmap="gray")

# 使用 Pyzbar 解码条形码
decoded_objects = decode(image)

# 检查是否检测到条形码
if decoded_objects:
    for obj in decoded_objects:
        print("Detected barcode content:", obj.data.decode("utf-8"))
else:
    print("No barcode detected")

Detected barcode content: https://www.tttttttttt.com
